---
# Tasks for deploying the backend
- name: Update and upgrade apt
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'
- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Create directory for backend
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
- name: Unarchive backend files
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend
- name: Export env variables
  become: yes  
  shell:  |    
    touch /etc/profile.d/env.sh
    echo export TYPEORM_HOST=$TYPTYPEORM_HOST >> /etc/profile.d/env.sh
    echo export TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> /etc/profile.d/env.sh
    echo export TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> /etc/profile.d/env.sh
    echo export TYPEORM_HOST=$TYPEORM_HOST >> /etc/profile.d/env.sh
    echo export TYPEORM_PORT=$TYPEORM_PORT >> /etc/profile.d/env.sh
    echo export TYPEORM_USERNAME=$TYPEORM_USERNAME >> /etc/profile.d/env.sh
    echo export TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> /etc/profile.d/env.sh
    echo export TYPEORM_DATABASE=$TYPEORM_DATABASE >> /etc/profile.d/env.sh
    echo export TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> /etc/profile.d/env.sh
    echo export TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> /etc/profile.d/env.sh
    . /etc/environment
    . ~/.bashrc
  register: execute_node

- name: Start app
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build
    cp package* ./dist
    cd dist
    npm i
    pm2 stop default
    pm2 start npm -- start
    cat ~/.pm2/logs/main-out.log