---
# Tasks for deploying the backend
- name: Update and upgrade apt
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'
- name: Install nodejs and npm
  become: true
  apt:
    name:
      - nodejs=13.8
      - npm
    state: latest
    update_cache: yes
- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Create directory for backend
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
- name: Copy backend files to new directory
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend
- name: unpack backend files
  become: yes
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
- name: start app
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env